apiVersion: apps/v1
kind: Deployment
metadata:
  name: llmops-rag
spec:
  replicas: 1
  selector:
    matchLabels:
      app: llmops-rag
  template:
    metadata:
      labels:
        app: llmops-rag
    spec:
      containers:
      - name: llmops-rag
        image: 598096478246.dkr.ecr.ap-south-1.amazonaws.com/llmops-rag:v2
        ports:
        - containerPort: 8000
        resources:
          requests:
            memory: "400Mi"
            cpu: "200m"
          limits:
            memory: "700Mi"
            cpu: "500m"
      - name: ollama
        image: ollama/ollama:latest
        ports:
        - containerPort: 11434
        resources:
          requests:
            memory: "500Mi"
            cpu: "200m"
          limits:
            memory: "900Mi"
            cpu: "700m"
        volumeMounts:
        - name: ollama-data
          mountPath: /root/.ollama
      volumes:
      - name: ollama-data
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: llmops-rag-service
spec:
  type: LoadBalancer
  selector:
    app: llmops-rag
  ports:
  - port: 80
    targetPort: 8000
